# Generated by Django 4.2.7 on 2026-02-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('user', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('request_body', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='aml_auditlo_timesta_ed7e12_idx'), models.Index(fields=['path'], name='aml_auditlo_path_3c9985_idx'), models.Index(fields=['user'], name='aml_auditlo_user_042343_idx')],
            },
        ),
    ]
